pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('SonarQube Analysis') {
            steps {
                script {
                    withSonarQubeEnv('sonar-server') {
                        sh "sonar-scanner -Dsonar.projectKey=terraform-template"
                    }
                }
            }
        }
        stage('Terraform Init/Plan') {
            steps {
                sh '''
                terraform init
                terraform plan -out=tfplan
                '''
            }
        }
        stage('Terraform Apply') {
            when { branch 'main' }
            steps {
                sh "terraform apply -auto-approve tfplan"
            }
        }
    }
}
